version: "3.8"

services:
  payara:
    container_name: payara-ewallet
    image: payara/server-full:6.2025.8-jdk17
    environment:
      - SECURE_ADMIN=true
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - ./webservice/target/webservice-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/webservice.war
      - ./webapp/target/webapp-1.0-SNAPSHOT.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/webapp.war